### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by FlorianLudwig** [Yakifo/aio-hbmqtt#1]
The original repo used tavis.

We could also check out gitlab actions.

Personally, I don't care.

**Comment by HerrMuellerluedenscheid** [comment]
I only used travis, jenkins, gitlab and drone ci thus far but always wanted to checkout github actions. I think this is a good opportunity getting to know that.

**Comment by HerrMuellerluedenscheid** [comment]
WIP in #5
