### ISSUE TITLE
Make tests run on CI

### ISSUE THREAD

**Issue by FlorianLudwig** [Yakifo/aio-hbmqtt#11]
Currently the CI fails due to port conflicts. See for example https://github.com/Yakifo/aio-hbmqtt/runs/2005741350

We need to investigate github actions or move to a different CI service

**Comment by HerrMuellerluedenscheid** [comment]
It's not related to the CI. It's a flaw in the tests. I have the feeling that the issue is related to concurrent asyncio loops which run wild. We should switch to `pytest` and `pytest-asyncio` which provide more control over the event loop.

**Comment by HerrMuellerluedenscheid** [comment]
Ci is fixed
